### ISSUE TITLE
some classes seem to get dropped when importing reablocks

### ISSUE THREAD

**Issue by steppy452** [reaviz/reablocks#10]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Unsure why this is happening and it's a little hard to know when it's going to happen. But here, is an example where the `start` attribute does not seem to get the css class when another repo imports reablocks. 

You'll have to inspect the svg icon and see that the containing div does not have a class.

But, if you look at reablocks storybook, you can see that there is a class `Input-module__start__####`
https://reablocks.dev/?path=/docs/components-form-input--start-adornment#start-adornment

## Expected behavior

I expect the start css classes to get passed through as well.

## Minimal reproduction of the problem with instructions

Here is a codesandbox which shows this happening:
https://codesandbox.io/s/cranky-monad-s0ptgj?file=/src/styles.css

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- reablocks version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by amcdnl** [comment]
PostCSS was dropping anything named 'start' or 'end' - no idea.
