### ISSUE TITLE
Usage of `navigator` with Next.js

### ISSUE THREAD

**Issue by gideonibemerejr** [reaviz/reablocks#161]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

 When using the components from `reaviz` in client components, the local development works, but compiling builds of any app will fail  with an error like so:

```
node_modules/reablocks/dist/index.js (909:54) @ navigator
ReferenceError: navigator is not defined
```

## Expected behavior

The builds and local development function without these blocking errors

You're able to bypass this issue by using `next/dynamic` and dynamically importing **each and every component** in order to not have to check to see if the component is using `navigator` -- this is a work around, yes, but not ideal 😄 

## Minimal reproduction of the problem with instructions
When using `reaviz` which makes use of `reablocks` there are several components that make use of various utility functions that all make use of `navigator`. 
1. Import any number of `reaviz` components that make use of `reablocks` 
2. Start your nextjs local dev with `npm run dev` and see the console for the error
3. Run `npm run build` 
4.  The build should fail with errors relating to pages not being able to be generated

## Environment

<pre><code>
Libs:
-next version: 14.1.0
- reablocks version: 7.3.4
- typescript version: 5.3.3

Browser:
- [x] Chrome (desktop) version 124.0.6367.93 (Official Build) (arm64)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v20.12.2  
- Platform:  Mac 

Others:

</code></pre>

**Comment by amcdnl** [comment]
@gideonibemerejr - Thanks for the ticket. I pushed up a release that should patch most of the issues, can you give it a try and let me know if you still have issues?

**Comment by amcdnl** [comment]
@gideonibemerejr - give it a shot now.
