### ISSUE TITLE
defaultProps Deprecated (And Causing Warnings)

### ISSUE THREAD

**Issue by jwalkerinterpres** [reaviz/reablocks#168]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe: Warning report
</code></pre>

## Current behavior

![image](https://github.com/reaviz/reablocks/assets/152227747/895dda53-2f3c-4f8a-ba1a-028abc9eced0)
![image](https://github.com/reaviz/reablocks/assets/152227747/ef120579-7513-4a04-be01-03291a54213d)
etc.

## Expected behavior

The console should be free of warnings.

## Minimal reproduction of the problem with instructions

1. Use any of the Rea Blocks components listed here: https://github.com/search?q=repo%3Areaviz%2Freablocks%20defaultProps&type=code
2. See the warnings shown above

## What is the motivation / use case for changing the behavior?

Signal to noise ratio: when my console is filled with warnings, it's harder to find the information I'm looking for in it.

## Environment

<pre><code>
Libs:
- react version: 18.2.0
- reablocks version: 5.10.14

Browser:
Irrelevant (warnings appear in all browsers/versions, as far as I know)

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jwalkerinterpres** [comment]
Y'all rock, thanks for addressing this!

**Comment by ghsteff** [comment]
> Y'all rock, thanks for addressing this!

No problem! 🙌
