### ISSUE TITLE
Select menu position is not updated after height is changed

### ISSUE THREAD

**Issue by SerhiiTsybulskyi** [reaviz/reablocks#234]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Select menu stay at top after menu height is changes

## Expected behavior
Select menu should be sticky to input

## Minimal reproduction of the problem with instructions

https://github.com/reaviz/reablocks/assets/5399389/3282ba60-7b6e-4ca7-9910-0ecbf2d20278

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- reablocks version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 125
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by amcdnl** [comment]
@SerhiiTsybulskyi - This is probably related to the popper migration.

**Comment by amcdnl** [comment]
Odd - basically on chane you should be able to trigger window resize which will cause it to update.

**Comment by SerhiiTsybulskyi** [comment]
#235
