### ISSUE TITLE
Select doesn't close menu onBlur if `closeOnSelect` is true

### ISSUE THREAD

**Issue by steppy452** [reaviz/reablocks#29]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If you have a multiselect dropdown, you'll probably enable `closeOnSelect` to allow for multiple selections without having to reopen the menu. However, click away, the menu persists. If you tab away, that seems to work as I expect.

https://user-images.githubusercontent.com/1513140/225368588-b3cf4643-6d2c-4f79-9df5-6c233dc7f7f5.mov

## Expected behavior

If the select input loses focus, the menu options should also disappear.

## What is the motivation / use case for changing the behavior?

Better UX

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- reablocks version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by amcdnl** [comment]
@steppy452 - Is this still an issue?

**Comment by steppy452** [comment]
i think you fixed this. closing...
