### ISSUE TITLE
Select value disappears

### ISSUE THREAD

**Issue by steppy452** [reaviz/reablocks#30]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

This may be an edge case or uncommon thing, but if I submit a form from say, a different tab, and it errors, the width of the input gets set to 2px for some reason. Here's a quick video - pay attention to the width of the input.

https://user-images.githubusercontent.com/1513140/225547808-8b634740-64da-4905-b5f9-c020af94037b.mov

## Expected behavior

value is still visible 

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- reablocks version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by amcdnl** [comment]
@steppy452 - Is this still an issue?
