### ISSUE TITLE
Select within a Drawer does not close onBlur

### ISSUE THREAD

**Issue by steppy452** [reaviz/reablocks#32]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

A Select element inside of a layer element such as Drawer or Dialog will not close `onBlur`

## Expected behavior

Select elements will close `onBlur` by default

## Minimal reproduction of the problem with instructions
Made a little codesandbox to demo this. The select shown on the main page closes just fine onBlur, but the select in the Drawer does not:
https://codesandbox.io/s/cranky-monad-s0ptgj?file=/src/App.tsx

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- reablocks version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by amcdnl** [comment]
Its because of this ... https://github.com/reaviz/rdk/blob/master/src/ExitListener/useExitListener.tsx#L21

It was added because if you have a select inside of a menu it would close the select and menu rather than just close the menu. Any ideas for a better fix?

**Comment by steppy452** [comment]
🤔 let me think
