### ISSUE TITLE
DotsLoader only animates once

### ISSUE THREAD

**Issue by steppy452** [reaviz/reablocks#34]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

DotsLoader only animates one time which is nice, but should probably continuously animate

## Expected behavior

loader continuously animates while on screen

## Minimal reproduction of the problem with instructions

https://reablocks.dev/?path=/story/components-elements-loader-dots--simple

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- reablocks version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by amcdnl** [comment]
This is odd because it has a loop setup:

```
transition={{
          duration: speed * 4,
          ease: 'easeInOut',
          times: [0, 0.2, 0.5, 0.8, 1],
          loop: Infinity,
          repeatDelay: speed,
          delay: speed * i
        }}
```

**Comment by steppy452** [comment]
fixed here https://github.com/reaviz/reablocks/commit/6f137298f8ec1037f2d959b84b2a673399d83296
