### ISSUE TITLE
List content has `break-word: break-all` set as default which causes weird breaks

### ISSUE THREAD

**Issue by steppy452** [reaviz/reablocks#40]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

something that wraps within the list could potentially get cut off in a weird way (ie, in the middle of a word)
![image](https://github.com/reaviz/reablocks/assets/1513140/20aa6bfb-ece2-4486-9c3f-e4c6c2bf4ffe)

## Expected behavior

I'd expect the entire word to be on the next line

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- reablocks version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by amcdnl** [comment]
@steppy452 - Do you have an alternative suggestion?

**Comment by steppy452** [comment]
i think `break-word` would be a better default, but if the table is too narrow, we'll end up with overflow which. Though, arguably both options aren't great. `break-word` just seems less terrible at the moment

**Comment by amcdnl** [comment]
I resolved this.
