### ISSUE TITLE
Ellipsize component `limit` is ellipsizing inconsistently

### ISSUE THREAD

**Issue by steppy452** [reaviz/reablocks#45]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

the limit is set to `80` on the link but it's clearly inconsistent in how it ellipsizes
<img width="538" alt="image" src="https://github.com/reaviz/reablocks/assets/1513140/959f0b8b-ec10-419e-8202-840e57c2d97f">

## Expected behavior

I would expect to see 80 characters before `...` and no ellipsis if the value is not over 80 characters

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- reablocks version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by amcdnl** [comment]
This is by design - it tries to be smart. If you want something more specific - we should chat why.
